-- MySQL Script generated by MySQL Workbench
-- Sat Apr 19 15:25:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `chat` ;

-- -----------------------------------------------------
-- Table `chat`.`conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`conversations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `isGroup` TINYINT(1) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `fullName` VARCHAR(50) NOT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `isOnline` TINYINT(1) NULL DEFAULT '0',
  `lastActive` DATETIME NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat`.`conversation_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`conversation_members` (
  `conversationId` INT NOT NULL,
  `userId` INT NOT NULL,
  `joinedAt` DATETIME NULL DEFAULT now(),
  `role` ENUM('admin', 'subadmin', 'member') NULL DEFAULT NULL,
  PRIMARY KEY (`conversationId`, `userId`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `conversation_members_ibfk_1`
    FOREIGN KEY (`conversationId`)
    REFERENCES `chat`.`conversations` (`id`),
  CONSTRAINT `conversation_members_ibfk_2`
    FOREIGN KEY (`userId`)
    REFERENCES `chat`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`friends` (
  `userId` INT NOT NULL,
  `friendId` INT NOT NULL,
  `status` ENUM('pending, accepted, block') NULL DEFAULT NULL,
  `createAt` DATETIME NULL DEFAULT now(),
  `acceptedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`userId`, `friendId`),
  INDEX `friendId` (`friendId` ASC) VISIBLE,
  CONSTRAINT `friends_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `chat`.`users` (`id`),
  CONSTRAINT `friends_ibfk_2`
    FOREIGN KEY (`friendId`)
    REFERENCES `chat`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conversationId` INT NOT NULL,
  `senderId` INT NOT NULL,
  `content` TEXT NOT NULL,
  `fileUrl` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `conversationId` (`conversationId` ASC) VISIBLE,
  INDEX `senderId` (`senderId` ASC) VISIBLE,
  CONSTRAINT `messages_ibfk_1`
    FOREIGN KEY (`conversationId`)
    REFERENCES `chat`.`conversations` (`id`),
  CONSTRAINT `messages_ibfk_2`
    FOREIGN KEY (`senderId`)
    REFERENCES `chat`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat`.`message_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`message_status` (
  `messageId` INT NOT NULL,
  `userId` INT NOT NULL,
  `isRead` TINYINT(1) NULL DEFAULT '0',
  `readedAt` DATETIME NULL DEFAULT NULL,
  INDEX `messageId` (`messageId` ASC) VISIBLE,
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `message_status_ibfk_1`
    FOREIGN KEY (`messageId`)
    REFERENCES `chat`.`messages` (`id`),
  CONSTRAINT `message_status_ibfk_2`
    FOREIGN KEY (`userId`)
    REFERENCES `chat`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
